language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql -e 'create database IF NOT EXISTS myguestbook'
  - mysql myguestbook < src/myguestbook.sql
  - pyrus set auto_discover 1
  - pyrus install --force phpunit/DbUnit
  - cd tests

script:
  - phpunit .

notifications:
  email: false
